---
- name: Manage Linux groups
  group:
    gid:    "{{ group.gid | default(omit) }}"
    local:  "{{ group.local | default(omit) }}"
    name:   "{{ group.name }}"
    state:  "{{ group.state | default('present') }}"
    system: "{{ group.system | default(omit) }}"
  loop: "{{ linux_groups }}"
  loop_control:
    loop_var: group
    label: "{{ group.name }} to be {{ group.state | default('present') }}"

- name: Add primary groups for present users
  group:
    name:   "{{ user.group | default(user.name) }}"
    state:  present
  loop: "{{ linux_users | selectattr2('state', '==', 'present', default='present') | list }}"
  loop_control:
    loop_var: user
    label: "{{ user.name }}"
